### ISSUE TITLE
Distortion of wav generated by the pre-trained model

### ISSUE THREAD

**Issue by oshindow** [YangAi520/NSPP#1]
hi, 
I'm trying to generate wav from the pre-trained model `NSPP_02100000` with the defalut config.json modifing the checkpoint_file_load and test_input_wav_dir only. The test wav is p278_002.wav in VCTK, but the generated wav was distortied. The tone of output wav is strange.

**Comment by YangAi520** [comment]
I am sorry. I made a little mistake while tidying up the code. In line 79 of `model.py`, the positions of `pseudo_imaginary_part` and `pseudo_real_part` need to be reversed. I have modified it and updated the code. You can try it again. The pre-trained model `NSPP_02100000` is trained using the updated code, so it exists distortion when using the original code. Thanks for your question.

**Comment by YangAi520** [comment]
> hi, I'm trying to generate wav from the pre-trained model `NSPP_02100000` with the defalut config.json modifing the checkpoint_file_load and test_input_wav_dir only. The test wav is p278_002.wav in VCTK, but the generated wav was distortied. The tone of output wav is strange.

I am sorry. I made a little mistake while tidying up the code. In line 79 of `model.py`, the positions of `pseudo_imaginary_part` and `pseudo_real_part` need to be reversed. I have modified it and updated the code. You can try it again. The pre-trained model `NSPP_02100000` is trained using the updated code, so it exists distortion when using the original code. Thanks for your question.

**Comment by oshindow** [comment]
Solved this problem. Amazing model!
